### ISSUE TITLE
服务容器化

### ISSUE THREAD

**Issue by SniperZhang** [UFEzhaoneng/myGolangProject#10]
将已有服务容器化，要求
* 每个服务编写Dockerfile，服务动态编译
* 服务以容器模式拉起后可正常互相通信
 * client正常访问，逻辑正确。

**Comment by UFEzhaoneng** [comment]
本周工作总结：
&nbsp; &nbsp;1. 已有功能优化 （Done）
&nbsp; &nbsp;3. 将已有功能容器化 （30%）


下周工作计划：
&nbsp; &nbsp;1. 将已有功能容器化
&nbsp; &nbsp;2. 实现发布的新需求


相关问题：
&nbsp; &nbsp;1. 遗留问题待解决







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Sniper Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月17日(星期五) 晚上7:43
收件人:&nbsp;"UFEzhaoneng/myGolangProject"<myGolangProject@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[UFEzhaoneng/myGolangProject] 服务容器化 (#10)





 
将已有服务容器化，要求
  
每个服务编写Dockerfile，服务动态编译
 
服务以容器模式拉起后可正常互相通信
 
client正常访问，逻辑正确。
