### ISSUE TITLE
Dockerfile build 后报错找不到package "google.golang.org"

### ISSUE THREAD

**Issue by UFEzhaoneng** [UFEzhaoneng/myGolangProject#14]
Docker 中已go get 过依赖包，但是go build 时提示未找到
我已进入过中间层镜像查找路径，发现的确没有下载依赖包：路径：/go/src

**Comment by SniperZhang** [comment]
> Docker 中已go get 过依赖包，但是go build 时提示未找到
> 我已进入过中间层镜像查找路径，发现的确没有下载依赖包：路径：/go/src

对应的Dockerfile可以贴一下。

**Comment by UFEzhaoneng** [comment]
FROM golang

# git

RUN apt-get update && \
    apt-get install unzip git

# grpc support
RUN PB_REL="https://github.com/protocolbuffers/protobuf/releases" && \
    curl -LO $PB_REL/download/v3.11.4/protoc-3.11.4-linux-x86_64.zip && \
    unzip protoc-3.11.4-linux-x86_64.zip -d /usr/local && \
    export PATH=$PATH:/usr/local/bin

RUN export GO111MODULE=on && \
    export GOPROXY=https://mirrors.aliyun.com/goproxy/ && \
    go get google.golang.org/grpc@v1.28.1 && \
    go get github.com/golang/protobuf/protoc-gen-go && \
    export PATH=$PATH:$GOPATH/bin

WORKDIR $GOPATH/src/mygolangproject
COPY . $GOPATH/src/mygolangproject
RUN cd  $GOPATH/src/mygolangproject/proto && \
    protoc --go_out=plugins=grpc:. service.proto && \
    go build $GOPATH/src/mygolangproject/grpcserver/my_grpc_server.go

EXPOSE 8000
ENTRYPOINT ["./mygolangproject"]

**Comment by SniperZhang** [comment]
当前代码中存在相对路径，如
```
package main

import (
        .....

	pb "./proto"
	...
)
```
找个对代码编译时依赖查找会有影响，可修改方式
* 全路径：即包含仓库地址信息，如
  ```
  import (
       "github.com/UFEzhaoneng/myGolangProject/proto"
  )
  ```

* 或者项目路径，如
  ```
  import (
       "mygolangproject/proto"
  )
  ```

**Comment by SniperZhang** [comment]
golang里的pacakge管理这块可以关注下，特别是当前go mod 模式。

**Comment by UFEzhaoneng** [comment]
相对路径问题我已经解决了，在issue#10中已经改为了绝对路径，只是GitPath中的包未能下载
