### ISSUE TITLE
镜像制作以及容器启动脚本

### ISSUE THREAD

**Issue by UFEzhaoneng** [UFEzhaoneng/myGolangProject#16]
在工程目录下构建镜像：
docker build -t grpc --target grpc .
docker build -t server --target server .
docker build -t client --target client .
容器启动脚本：
docker run -it --net host grpc
docker run -it --net host server
docker run -it --net host client

**Comment by SniperZhang** [comment]
### 关于本issue Dockerfile可考虑点
1. client端不依赖环境，一般无特殊需要，针对server端进行容器化即可；
2. 当前多个镜像复用了一个Dockerfile，扩展性可能会受限，实际使用一般一个镜像一个Dockerfile。
3. 可以关注下GO111MODULE不同值的含义，采用go mod模式可不用与GOPATH关联。
4. 当前以交互模式启动容器，实际运行需要以background后台模式运行，可以关注下常用的-d, -v, -p , --restart 等参数。

**Comment by UFEzhaoneng** [comment]
在工程目录下构建镜像（其中将http server中与grpc连接的ip改回127.0.0.1）：
docker build -f server_docker_file -t server .
docker build -f grpc_docker_file -t grpc .
在本地 go build client
容器启动脚本：
docker run -it --net host grpc
docker run -it --net host server
在本地 go run client后失败
报错：2020/05/07 21:12:38 Post "http://127.0.0.1:8089/register": dial tcp 127.0.0.1:8089: connectex: No connection could be made because the target machine actively refused it.
