### ISSUE TITLE
server端增加功能

### ISSUE THREAD

**Issue by SniperZhang** [UFEzhaoneng/myGolangProject#2]
### 学生信息包括
*  学号:  保持唯一
*  姓名:  仅支持英文，必须
*  年龄:  整数，必须，范围[10, 100]
*  专业：枚举值，“计算机科学与技术“或“软件工程”，必须

### 操作支持
*  学生信息创建：
    * 请求：姓名，年龄，专业
    * 返回:  学号
*  学生查询：
    * 请求：学号
    * 返回：学生信息
*  修改学生专业
    *  请求：学号
    *  返回：成功或失败
* 删除
   * 请求：学号
   * 返回：成功或失败

### 实现要求
   当前仅做练习，可使用内存实现，后续用数据库实现持久化存储。

**Comment by UFEzhaoneng** [comment]
本周工作总结：
&nbsp; &nbsp;1. 作业： 在原有服务的基础上，新增学生信息管理功能&nbsp;（Done）
&nbsp; &nbsp;2. Docker学习（30%）


&nbsp; &nbsp;下周工作计划：
&nbsp; &nbsp;1. 针对作业的不足进行改进
&nbsp; &nbsp;2. Docker学习
&nbsp; &nbsp;3. 完成作业：创建镜像并启动所有服务进行通信


&nbsp; &nbsp;相关问题：
&nbsp; &nbsp;1. 想要将连接grpc服务器的行为封成函数，返回值如何设计比较好





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Sniper Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月11日(星期六) 凌晨0:02
收件人:&nbsp;"UFEzhaoneng/myGolangProject"<myGolangProject@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[UFEzhaoneng/myGolangProject] server端增加功能 (#2)





 
后端提供学生信息的维护
 
学生信息包括
  
学号:  保持唯一
 
姓名:  仅支持英文，必须
 
年龄:  整数，必须，范围[10, 100]
 
专业：枚举值，“计算机科学与技术“或“软件工程”，必须
  
操作支持
  
学生信息创建：  
请求：姓名，年龄，专业
 
返回:  学号
  
 
学生查询：  
请求：学号
 
返回：学生信息
  
 
修改学生专业  
请求：学号
 
返回：成功或失败
  
 
删除  
请求：学号
 
返回：成功或失败
  
  
实现要求
 
当前仅做练习，可使用内存实现，后续用数据库实现持久化存储。
